name: check-pr-branches
description: A action to check if I my PR branches is allowed.
author: Italojs
branding:
  icon: 'thumbs-up'
  color: 'white'

runs:
  using: "composite"
  steps:
      - name : Verifing branches
        run: if [ ${{ github.base_ref }} = "master" ] && [ ${REF_BRANCH:0:7} != "release" ]; then exit 1; fi
        env:
          REF_BRANCH: ${{ github.event.pull_request.head.ref }}
        shell: bash
