name: check-pr-branches
description: A action to check if I my PR branches is allowed.
author: Italojs
branding:
  icon: 'thumbs-up'
  color: 'white'

inputs:
  regex4base:
    description: 'Define env name'     
    required: true
    default: ''
  regex4compare:
    description: 'Define env name'     
    required: true
    default: 'prod'
        
runs:
  using: "composite"
  steps:
      - name : Verifing branches
        run: |
            if [[ $BASE_BRANCH =~ $BASE_REGEX ]] && [[ $COMPARE_BRANCH =~ $COMPARE_REGEX ]]
            then 
              echo merge $BASE_BRANCH into $COMPARE_BRANCH allowed! (ɔ◔‿◔)ɔ ♥
            else
              echo merge $BASE_BRANCH into $COMPARE_BRANCH denied. (ಥ_ಥ)
              echo Merges into $BASE_BRANCH is only permitted when 'compare' branch match with regex $COMPARE_REGEX! (◐.̃◐)
              exit 1
            fi
        env:
          COMPARE_BRANCH: ${{ github.event.pull_request.head.ref }}
          BASE_BRANCH: ${{ github.base_ref }}
          COMPARE_REGEX: ${{ inputs.regex4compare }}
          BASE_REGEX: ${{ inputs.regex4base }}
        shell: bash
      
