name: check-pr-branches
description: A action to check if I my PR branches is allowed.
author: Italojs
branding:
  icon: 'thumbs-up'
  color: 'white'

inputs:
  contains_in_base:
    description: 'Define env name'     
    required: true
    default: 'prod'
  contains_in_compare:
    description: 'Define env name'     
    required: true
    default: 'prod'
        
runs:
  using: "composite"
  steps:
      - name : Verifing branches
        run: |
            echo "Env: ${{ github.event.inputs.contains_in_base }}" 
            echo "Branch: ${{ github.event.inputs.contains_in_compare }}"
            echo "github_base_ref: ${{ github.base_ref }}"
            echo "github_event_pull_request_ref: ${{ github.event.pull_request.head.ref }}"
            if [ ${{ github.base_ref }} = "master" ] && [ ${REF_BRANCH:0:7} != "release" ]; then exit 1; fi
        env:
          REF_BRANCH: ${{ github.event.pull_request.head.ref }}
        shell: bash
      
