name: check-pr-branches
description: A action to check if I my PR branches is allowed.
author: Italojs
branding:
  icon: 'thumbs-up'
  color: 'white'

inputs:
  base:
    description: 'Define env name'     
    required: true
    default: ''
  compare:
    description: 'Define env name'     
    required: true
    default: 'prod'
        
runs:
  using: "composite"
  steps:
      - name : Verifing branches
        run: |
            echo "github.event.pull_request.head.ref: $(${{ github.event.pull_request.head.ref }}):0:7"
            REF_BRANCH=${{ inputs.compare }} echo "REF_BRANCH: ${REF_BRANCH:0:7}"
            if [ ${{ github.base_ref }} = ${{ inputs.base }} ] && [ ${REF_BRANCH:0:7} != "release" ]; then exit 1; fi
        env:
          REF_BRANCH: ${{ github.event.pull_request.head.ref }}
        shell: bash
      
