name: check-pr-branches
description: An action to check if my PR branches is allowed to merge.
author: Italojs
branding:
  icon: 'check-square'
  color: 'green'

inputs:
  when_base:
    description: 'Define base branch name (we accept regex)'     
    required: true
  allow_only:
    description: 'Define compare branch name (we accept regex)'     
    required: true
        
runs:
  using: "composite"
  steps:
      - name : Checking branches
        run: |
            if [[ $BASE_BRANCH =~ $BASE_REGEX ]] && ! [[ $COMPARE_BRANCH =~ $COMPARE_REGEX ]]
            then 
                echo "Merge $BASE_BRANCH into $COMPARE_BRANCH denied. (ಥ_ಥ)
                Merges into $BASE_BRANCH is only permitted when 'compare' branch match with regex '$COMPARE_REGEX'! (◐.̃◐)"
                exit 1
            else
                echo "Merge $BASE_BRANCH into $COMPARE_BRANCH allowed! (ɔ◔‿◔)ɔ ♥"
            fi
        env:
          COMPARE_BRANCH: ${{ github.event.pull_request.head.ref }}
          BASE_BRANCH: ${{ github.base_ref }}
          COMPARE_REGEX: ${{ inputs.regex4compare }}
          BASE_REGEX: ${{ inputs.regex4base }}
        shell: bash
      
